import type { NewsItem, Topic } from '../db/schemas.js';

/**
 * Turning stories into the scenes of a briefing reel (NEWS-167, docs/27 §27.6).
 *
 * Pure string-building only — no filesystem, no subprocess. Staging the files
 * and running domotion is `stage.ts`'s job. Keeping the markup generation
 * separable is what lets the interesting rules here (which story gets the
 * long-headline treatment, what happens with no photo, and above all that no
 * remote URL can reach the page) be tested without a browser anywhere near it.
 *
 * The design lives in `cards/cards.css`. This module only decides *which*
 * classes and content a card gets.
 */

/** Escape the five HTML-significant characters. Every interpolated value goes through this. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Above this many characters a headline gets the smaller step (FR-27.21).
 *
 * Tuned against the reviewed stills rather than derived: at 82px on a 1080px
 * canvas, roughly this much text is the point where a headline stops fitting
 * the space the card gives it. It steps down rather than clamping because
 * losing the end of a headline is worse than setting it smaller — it is the
 * one line that says what the story is.
 */
export const LONG_HEADLINE_CHARS = 68;

/** Where a card's photo comes from — a staged local file, or nothing. */
export type CardPhoto = { file: string } | null;

export interface StoryCardInput {
  item: NewsItem;
  topic: Topic | undefined;
  /** Already-resolved outlet name (the app's `outletFor`), so this stays pure. */
  outlet: string;
  /** Already-formatted date, e.g. "29 Jul". */
  dateLabel: string;
  photo: CardPhoto;
}

/**
 * A story card.
 *
 * `.rule` is always in the markup and shown by CSS only on the no-photo card —
 * the same always-present-container discipline the client's kerf rules use, so
 * the two card shapes differ by class rather than by structure.
 */
export function storyCardHtml(input: StoryCardInput): string {
  const { item, topic, outlet, dateLabel, photo } = input;
  const kicker = topic?.name ?? 'Newsmonger';
  const long = item.title.length > LONG_HEADLINE_CHARS;
  const sources = item.sources.length;
  const sourceLabel = sources === 1 ? '1 source' : `${String(sources)} sources`;

  const media = photo === null ? '' : `\n  <div class="media"><img src="${escapeHtml(photo.file)}" alt=""></div>`;

  return `<!doctype html>
<meta charset="utf-8">
<link rel="stylesheet" href="cards.css">
<title>${escapeHtml(item.title)}</title>
<body${photo === null ? ' class="no-media"' : ''}>${media}
  <div class="body">
    <div class="rule"></div>
    <div class="kicker">${escapeHtml(kicker)}</div>
    <h1 class="headline${long ? ' is-long' : ''}">${escapeHtml(item.title)}</h1>
    <p class="deck">${escapeHtml(item.summary)}</p>
    <div class="attribution">
      <span class="outlet">${escapeHtml(outlet)}</span>
      <span class="meta">${escapeHtml(sourceLabel)} &middot; ${escapeHtml(dateLabel)}</span>
    </div>
  </div>
</body>
`;
}

/** The opening card: what day this is and how much there is. */
export function titleCardHtml(opts: { dateLabel: string; storyCount: number; topicCount: number }): string {
  const stories = opts.storyCount === 1 ? '1 new story' : `${String(opts.storyCount)} new stories`;
  const topics = opts.topicCount === 1 ? '1 topic' : `${String(opts.topicCount)} topics`;
  return `<!doctype html>
<meta charset="utf-8">
<link rel="stylesheet" href="cards.css">
<title>Briefing</title>
<body>
  <div class="centered">
    <div class="title-eyebrow">The overnight briefing</div>
    <h1 class="title-main">${escapeHtml(opts.dateLabel)}</h1>
    <div class="title-sub">${escapeHtml(stories)} across ${escapeHtml(topics)}</div>
  </div>
</body>
`;
}

/**
 * The closing card (FR-27.7).
 *
 * The only branded scene in the reel, and the only place the AI disclosure
 * appears (FR-27.6) — story cards stay unbranded so the outlet's name is the
 * only attribution competing for attention on them.
 */
export function endCardHtml(opts: { dateLabel: string; storyCount: number; wordmarkFile: string }): string {
  const stories = opts.storyCount === 1 ? '1 story' : `${String(opts.storyCount)} stories`;
  return `<!doctype html>
<meta charset="utf-8">
<link rel="stylesheet" href="cards.css">
<title>Newsmonger</title>
<body>
  <div class="centered">
    <img class="endmark" src="${escapeHtml(opts.wordmarkFile)}" alt="Newsmonger">
    <div class="count">${escapeHtml(stories)} &middot; ${escapeHtml(opts.dateLabel)}</div>
    <p class="disclosure">Summaries generated by AI from the linked sources. Headlines and photographs belong to the publications credited.</p>
  </div>
</body>
`;
}

/**
 * Reject any markup that would make the browser talk to the network (FR-27.8).
 *
 * Domotion inlines whatever the page loads, so a capture page carrying a
 * publisher URL would put **Chromium** on the open internet — undoing FR-8.4's
 * guarantee that the app makes zero third-party requests. The failure is
 * silent: the rendered card looks identical either way, so nothing about the
 * output would ever reveal it.
 *
 * That is why this is an assertion in the pipeline rather than a comment
 * telling the next person to be careful. It runs over the generated HTML,
 * which is the last point where the whole page is visible as one string.
 */
export function assertNoRemoteRefs(html: string, where: string): void {
  const offenders = [...html.matchAll(/(?:src|href)\s*=\s*"([^"]*)"/gi)]
    .map((m) => m[1])
    .filter((url) => /^(?:[a-z][a-z0-9+.-]*:)?\/\//i.test(url) || /^(?:https?|data|blob):/i.test(url))
    // A loopback reference is the image route serving the local cache, which is
    // the sanctioned path — it is the publisher's own host that must never appear.
    .filter((url) => !/^https?:\/\/(?:127\.0\.0\.1|localhost|\[::1\])(?::\d+)?\//i.test(url));

  if (offenders.length > 0) {
    throw new Error(
      `${where}: capture HTML references non-local URLs, which would make the ` +
        `renderer fetch from the network and break the FR-8.4 image proxy: ${offenders.join(', ')}`,
    );
  }
}

/** One scene of the storyboard, before it is written to disk. */
export interface Scene {
  /** File name the HTML is staged under. */
  file: string;
  html: string;
  /** On-screen time in ms. */
  durationMs: number;
}

/**
 * How long a story card stays up.
 *
 * Reading time, not a fixed beat: a card the viewer cannot finish is wasted,
 * and one that lingers after they have finished drags. Roughly 25 characters a
 * second over the headline and deck, floored so a very short story still lands
 * and capped so a very long one does not stall the reel.
 */
export function storyDurationMs(item: NewsItem): number {
  const chars = item.title.length + item.summary.length;
  return Math.min(7000, Math.max(3200, Math.round((chars / 25) * 1000)));
}

export const TITLE_DURATION_MS = 2600;
export const END_DURATION_MS = 3400;

/**
 * The scene list for a reel.
 *
 * Every scene's HTML is checked for remote references as it is built, so a
 * mistake surfaces here rather than as a silent network fetch during capture.
 */
export function buildScenes(opts: {
  items: readonly NewsItem[];
  topics: readonly Topic[];
  outletFor: (item: NewsItem) => string;
  dateLabelFor: (iso: string) => string;
  /** Staged photo file for a story, or null when it has no usable image. */
  photoFor: (item: NewsItem) => CardPhoto;
  headerDateLabel: string;
  wordmarkFile: string;
}): Scene[] {
  const byId = new Map(opts.topics.map((t) => [t.id, t]));
  const topicIds = new Set(opts.items.map((i) => i.topicId));

  const scenes: Scene[] = [
    {
      file: 'scene-00-title.html',
      html: titleCardHtml({
        dateLabel: opts.headerDateLabel,
        storyCount: opts.items.length,
        topicCount: topicIds.size,
      }),
      durationMs: TITLE_DURATION_MS,
    },
  ];

  opts.items.forEach((item, index) => {
    scenes.push({
      file: `scene-${String(index + 1).padStart(2, '0')}-story.html`,
      html: storyCardHtml({
        item,
        topic: byId.get(item.topicId),
        outlet: opts.outletFor(item),
        dateLabel: opts.dateLabelFor(item.foundAt),
        photo: opts.photoFor(item),
      }),
      durationMs: storyDurationMs(item),
    });
  });

  scenes.push({
    file: `scene-${String(opts.items.length + 1).padStart(2, '0')}-end.html`,
    html: endCardHtml({
      dateLabel: opts.headerDateLabel,
      storyCount: opts.items.length,
      wordmarkFile: opts.wordmarkFile,
    }),
    durationMs: END_DURATION_MS,
  });

  for (const scene of scenes) assertNoRemoteRefs(scene.html, scene.file);
  return scenes;
}

/**
 * The storyboard config domotion renders.
 *
 * Transitions alternate between two families deliberately: a reel of identical
 * cuts reads as a slideshow. The last scene carries none — a storyboard loops,
 * and a transition on the final scene would animate the end card back into the
 * title, which reads as a glitch rather than as a loop.
 */
export function storyboardConfig(opts: {
  scenes: readonly Scene[];
  width: number;
  height: number;
  output: string;
  background: string;
}): unknown {
  return {
    width: opts.width,
    height: opts.height,
    output: opts.output,
    background: opts.background,
    scenes: opts.scenes.map((scene, index) => ({
      capture: { file: scene.file },
      duration: scene.durationMs,
      ...(index < opts.scenes.length - 1
        ? { transition: { type: index % 2 === 0 ? 'crossfade' : 'push-left', duration: 420 } }
        : {}),
    })),
  };
}

/**
 * The reel's total play length.
 *
 * The caller passes this to `svg-to-video --duration` rather than letting it
 * default (FR-27.13): the default is one seamless loop computed as the LCM of
 * every animation period in the document, and a single off-period decorative
 * loop silently multiplies the export by an integer factor.
 */
export function totalDurationMs(scenes: readonly Scene[]): number {
  return scenes.reduce((sum, scene) => sum + scene.durationMs, 0);
}
